name: 'Deploy Lambdas to Staging'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-west-2

concurrency: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  staging_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./apps/lambdas yarn deploy -s staging"
          entrypoint: /bin/sh
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
